name: movies_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  google_fonts: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.8 # Moved here

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/onBoarding/

flutter_native_splash:
  color: "#121312"
  image: assets/image/splash_screen_logo.png
  branding: assets/image/btn_splash_screen.png

  color_dark: "#121312"
  image_dark: assets/image/splash_screen_logo.png
  branding_dark: assets/image/btn_splash_screen.png

  android: true
  ios: true
  web: false

  android_12:
    image: assets/image/splash_screen_logo.png
    icon_background_color: "#121312"
    color: "#121312"
    branding: assets/image/btn_splash_screen.png
